// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// move the window to the center of screen and turn its
/// size to (1024 * 768)
void toCenter() => RustLib.instance.api.crateApiWindowManagerToCenter();
